name: "Build and Delpoy Billing Service to Cloud Run"

on:
  push:
    branches:
      - "master"

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  GCR_REGION: "${{ secrets.GCR_REGION }}"
  BILLING_GCR_SERVICE: "${{ secrets.BILLING_GCR_SERVICE }}"
  BILLING_IMAGE_NAME: "${{ vars.BILLING_IMAGE_NAME }}"
  GAR_NAME: "${{ secrets.GAR_NAME }}"
  GAR_REGION: "${{ secrets.GAR_REGION }}"
  BILLING_SUB_NAME: "${{ vars.BILLING_SUB_NAME }}"

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout Repo"
        uses: "actions/checkout@v4"

      - name: "Authenticate to GCP"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Docker Auth To GAR"
        run: |
          gcloud auth configure-docker "${{env.GAR_REGION}}-docker.pkg.dev"

      - name: "Build and Push To GAR"
        run: |-
          DOCKER_TAG="${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.BILLING_IMAGE_NAME }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" --build-arg PROJECT_ID="$PROJECT_ID" --build-arg SUBSCRIPTION_NAME="$BILLING_SUB_NAME" ./backend/billing-service
          docker push "${DOCKER_TAG}"

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME ${{ env.BILLING_GCR_SERVICE }}
          gcloud run deploy ${{ env.BILLING_GCR_SERVICE }} \
            --image ${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.BILLING_IMAGE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region ${{ env.GCR_REGION }} \
            --port 8080 \
            --allow-unauthenticated

      - name: "Show output"
        run: |2-
          echo ${{ steps.deploy.outputs.url }}